### ISSUE TITLE
Using the given model，PSNR-u is lower than the cvpr repoerted

### ISSUE THREAD

**Issue by LiuzhuForFun** [qingsenyangit/AHDRNet#14]
def range_compressor_tensor(x):
    const_1 = torch.from_numpy(np.array(1.0)).cuda()
    const_5000 = torch.from_numpy(np.array(5000.0)).cuda()
    return (torch.log(const_1 + const_5000 * x)) / torch.log(const_1 + const_5000)
Is this fuction not correct?
Thanks

**Comment by wensongc** [comment]
大佬，我用这里的pt文件，复现的结果比论文低，请问你复现出来论文的结果了吗？

**Comment by LiuzhuForFun** [comment]
可以



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 24, 2022 11:13 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [qingsenyangit/AHDRNet] Using the given model，PSNR-u is lower than the cvpr repoerted (Issue #14)




 
大佬，我用这里的pt文件，复现的结果比论文低，请问你复现出来论文的结果了吗？

**Comment by wensongc** [comment]
谢谢大佬回复，是需要继续训练还是直接用这里面的pt文件就可以呀？

**Comment by LiuzhuForFun** [comment]
重新训练一下吧

**Comment by LiuzhuForFun** [comment]
通过调学习率能收敛

**Comment by wensongc** [comment]
明白了，感谢大佬！
