### ISSUE TITLE
Washed-out colors

### ISSUE THREAD

**Issue by Anna-Szal** [qingsenyangit/AHDRNet#18]
Hello,
I can't seem to get the kind of beautiful saturated colors from the paper using this code.. I understand that the main contribution of your paper is a ghost-free image, and dealing with motion, not colors. Does this mean you used some additional color mapping or maybe tweaked the colors manually using some image editing software just for the paper? Or am I missing something obvious?

**Comment by Zasion** [comment]
I encountered the same situation as you, did you solve it?

**Comment by Anna-Szal** [comment]
Well, sort of.. The AHDRNet and all similar models merge 3 photos into one, where pixel values have range far greater than 256 (the HDR), which also means you cannot visualize it easily - your image viewer will probably just trim the values and you'll get a very dark image. So you need some kind of tone mapping (from high range to 256 values) - either do it manually in a Photoshop-like editor, or develop an algorithm (or another neural model). The authors here use a very primitive tone mapping operator, this one:
output = torch.log(1 + 5000 * output.cpu()) / torch.log(Variable(torch.from_numpy(np.array([1+5000])).float()))

Every other paper that used this operator with this dataset reported similar washed-out colored pictures, except for one - it had vivid colors, but the authors explicitly stated that they used image editor afterwards, so I guess it's safe to say that the authors of the AHDRNet did the same thing.

**Comment by Zasion** [comment]
Sincerely appreciate your answer : ) , I have solved this problem on MATLAB with tonemap function[tonemap(data,'AdjustLightness',[0,1],'AdjustSaturation',6)]. And I got a similar effect to the author's. My supervisor reminded me to read the paper carefully, I should have realized this problem earlier. Thank you again! Love from CN ❤️

**Comment by Anna-Szal** [comment]
Huh, well that makes at least two of us, can't believe i missed this :D 
I remember i used some openCV functions instead, but maybe this one is better :)
